title: Ivete Tecedor
baseurl: ""
url: "https://ivetetecedor.com" 
twitter_username: 
github_username:  itecedor

# Build settings
plugins:
  - jekyll-feed

collections:
  projects:
    output: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
